### ISSUE TITLE
Проблема с getCountTotal

### ISSUE THREAD

**Issue by sax0n0xas** [Imhonet-ru/Connection#30]
getCountTotal возвращает неправильные данные.
кейс такой. запрос с limit. получаем данные. делаем getCountTotal и получаем неверный результат.

хотя если запрос с limit. делаем getCountTotal и получаем верный результат.

проблема где-то в Imhonet\Connection\Query\PDO\MySQL.php в getCountTotal в последовательности ифов.

**Comment by Serjick** [comment]
Fixed by #55
